export const USER_EVENTS = {
  ADD_TODO: 'ADD_TODO',
  TOGGLE_TODO: 'TOGGLE_TODO',
  DELETE_TODO: 'DELETE_TODO',
  CLEAR_ALL_TODOS: 'CLEAR_ALL_TODOS'
};

export const FILTER_EVENTS = {
  FILTER_ALL: 'FILTER_ALL',
  FILTER_INCOMPLETE: 'FILTER_INCOMPLETE',
  FILTER_COMPLETED: 'FILTER_COMPLETED',
  ALL: 'All',
  INCOMPLETE: 'Incomplete',
  COMPLETED: 'Completed'
};